Repository esphome/esphome-devices, pull requests merged in 2025-02, with the labels that each got.

#1018 Sonoff S31 - Powering Relay Coil in Example May Damage UART Adapters
  src/docs/devices/Sonoff-S31/index.md
Labels: documentation

#1023 Mark SmartPad EM32 Smart Plug as Made for ESPHome
  src/docs/devices/smartpad-em32-smart-plug/index.md
Labels: made-for-esphome-approved

#1024 Mark Nerdiy's SelfIY Ring as Made for ESPHome
  src/docs/devices/SelfIY-Ring-by-Nerdiy/index.md
Labels: made-for-esphome-approved

#1033 Added SiloCityLabs dikale filament dryer pcb
  src/docs/devices/SiloCityLabs-Dikale-Filament-Dryer/index.md
Labels: made-for-esphome-approved, made-for-esphome
